export const YC_SCHEMA_LABELS: Record<string, string> = {
  Address: 'Адреса',
  Airplane: 'Літак',
  Analyzable: 'Аналітична сутність',
  Article: 'Стаття',
  Assessment: 'Оцінка',
  Asset: 'Актив',
  Associate: 'Пов’язана особа',
  Audio: 'Аудіо',
  BankAccount: 'Банківський рахунок',
  Call: 'Дзвінок',
  Company: 'Компанія',
  Contract: 'Контракт',
  ContractAward: 'Присудження контракту',
  CourtCase: 'Судова справа',
  CourtCaseParty: 'Сторона судової справи',
  CryptoWallet: 'Криптогаманець',
  Debt: 'Борг',
  Directorship: 'Керівна посада',
  Document: 'Документ',
  Documentation: 'Документація',
  EconomicActivity: 'Економічна діяльність',
  Email: 'Email',
  Employment: 'Працевлаштування',
  Event: 'Подія',
  Family: 'Сімейний зв’язок',
  Folder: 'Папка',
  HyperText: 'Гіпертекст',
  Identification: 'Ідентифікація',
  Image: 'Зображення',
  Interest: 'Інтерес',
  Interval: 'Інтервал',
  LegalEntity: 'Юридична особа',
  License: 'Ліцензія',
  Membership: 'Членство',
  Mention: 'Згадка',
  Note: 'Нотатка',
  Organization: 'Організація',
  Ownership: 'Володіння',
  Package: 'Пакет',
  Page: 'Сторінка',
  Passport: 'Паспорт',
  Payment: 'Платіж',
  Person: 'Фізична особа',
  PlainText: 'Текст',
  Post: 'Публікація',
  ProjectParticipant: 'Учасник проєкту',
  PublicBody: 'Державний орган',
  RealEstate: 'Нерухомість',
  RepOrganization: 'Представництво організації',
  RepPerson: 'Представник фізичної особи',
  Representation: 'Представництво',
  RepVessel: 'Представництво судна',
  Sanction: 'Санкція',
  Security: 'Цінний папір',
  Similar: 'Подібна сутність',
  Succession: 'Правонаступництво',
  Table: 'Таблиця',
  TaxRoll: 'Податковий запис',
  Thing: 'Сутність',
  UnknownLink: 'Невідомий зв’язок',
  UserAccount: 'Обліковий запис',
  Value: 'Значення',
  Vehicle: 'Транспортний засіб',
  Vessel: 'Судно',
  Video: 'Відео',
  Workbook: 'Робоча книга',
};
